In [1]:
import numpy as np

In [2]:
X = np.random.randint(0,2,(7,3))

In [3]:
X[:,-1]=1

In [4]:
X[:5,:]

array([[0, 1, 1],
       [0, 1, 1],
       [1, 0, 1],
       [0, 1, 1],
       [1, 1, 1]])

In [5]:
from sklearn.neural_network import MLPRegressor

In [6]:
mlp = MLPRegressor(solver='lbfgs',activation='logistic', alpha=1e-3, hidden_layer_sizes=(2,1,2),max_iter=800000)

Train the network (fit)

In [7]:
mlp.fit(X,X)

MLPRegressor(activation='logistic', alpha=0.001, hidden_layer_sizes=(2, 1, 2),
             max_iter=800000, solver='lbfgs')

Test the model

In [8]:
predictions = mlp.predict(X)

Create classification report and confusion matrix

In [9]:
aa = (predictions > 0.5) ^ (X == 1)

In [10]:
np.count_nonzero(aa)

1

In [11]:
predictions

array([[ 0.1003345 ,  1.03544976,  0.99915064],
       [ 0.1003345 ,  1.03544976,  0.99915064],
       [ 0.5803487 , -0.16068011,  1.00180385],
       [ 0.1003345 ,  1.03544976,  0.99915064],
       [ 0.2353132 ,  0.69735278,  0.99985314],
       [ 0.44139833,  0.17809264,  1.0008496 ],
       [ 0.44139833,  0.17809264,  1.0008496 ]])

In [12]:
for i in mlp.coefs_:
    print (i)
    print("******")

[[-0.43514078  1.22422533]
 [ 1.17324823 -2.22898533]
 [-0.17249257  0.28621375]]
******
[[ 1.40519095]
 [-2.46346818]]
******
[[ 3.14081869 -1.01486689]]
******
[[-1.01478075  3.44735967  0.01728424]
 [ 0.79741192  0.94457508  0.077464  ]]
******


In [13]:
mlp.intercepts_

[array([0.05318448, 0.30616891]),
 array([0.54700225]),
 array([-1.59104766, -0.04177584]),
 array([ 0.56002278, -1.64368628,  0.96347252])]

In [14]:
mlp.predict(np.array([0,1,1]).reshape(1,-1))

array([[0.1003345 , 1.03544976, 0.99915064]])

In [15]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

In [16]:
X

array([[0, 1, 1],
       [0, 1, 1],
       [1, 0, 1],
       [0, 1, 1],
       [1, 1, 1],
       [0, 0, 1],
       [0, 0, 1]])

In [17]:
s= X[2]
print(s)

[1 0 1]


In [18]:
l1 = sigmoid(np.dot(s,mlp.coefs_[0])+mlp.intercepts_[0])

In [19]:
l2 = sigmoid(np.dot(l1,mlp.coefs_[1])+mlp.intercepts_[1])

In [20]:
l3 = sigmoid(np.dot(l2,mlp.coefs_[2])+mlp.intercepts_[2])

In [21]:
l4 = np.dot(l3,mlp.coefs_[3])+mlp.intercepts_[3]

In [22]:
l4

array([ 0.5803487 , -0.16068011,  1.00180385])